env:
  commonjs: true
  es2021: true
  node: true
overrides: []
parserOptions:
  ecmaVersion: latest
rules: {
  indent: ['error', 2],
  quotes: ['error', 'single'],
  semi: ['error', 'always'],
  eqeqeq: 'error',
  no-trailing-spaces: 'error',
  object-curly-spacing: ['error', 'always'],
  arrow-spacing: ['error', { 'before': true, 'after': true }],
  linebreak-style: ['error', 'unix'],
  no-console: 0
}
